# Generated by Django 5.1.4 on 2025-01-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255)),
                ('минимальная_зарплата', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('максимальная_зарплата', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('валюта', models.CharField(max_length=10)),
                ('город', models.CharField(max_length=100)),
                ('дата_публикации', models.DateField()),
                ('key_skills', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
