# Generated by Django 5.1.4 on 2025-01-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBank_rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('rate', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
