# Generated by Django 5.1.4 on 2025-01-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_all_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_avg_salary_by_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
