# Generated by Django 5.1.4 on 2025-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_all_avg_salary_by_city_all_city_distribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_avg_salary_by_year',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_top_skills_by_year',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_top_skills_by_year',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='all_vacancies_by_year',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
